# Generated by Django 4.0 on 2021-12-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('submitted_by', models.CharField(max_length=255)),
                ('submission_date', models.DateField()),
                ('activity_date', models.DateField(blank=True)),
                ('activity_type', models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Hike', 'Hike'), ('Sport', 'Sport'), ('Other', 'Other')], max_length=255)),
                ('activity_address', models.CharField(blank=True, max_length=511)),
            ],
        ),
    ]
