# Generated by Django 4.0 on 2022-01-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bucketlist', '0002_activity_activity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_address',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Hike', 'Hike'), ('Sport', 'Sport'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='Placeholder', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='submitted_by',
            field=models.CharField(default='Placeholder', max_length=255),
        ),
    ]
